[profile.default]
src = "src"
out = "out"
remappings = ['@openzeppelin=lib/openzeppelin-contracts']
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
